#! /bin/sh

set -e

rm -f src/*.gcno # generated by make
rm -f src/*.gcda # generated during runtime
rm -f coverage.info
rm -rf out-test-coverage

echo "build"
make clean
make check

echo "run test";

./test-vlan0

echo "collect"
#gcov src/test_vlan0-vlan.o
gcov src/test_vlan0-*.o
#lcov --coverage --directory src --output-file coverage.info
lcov --capture --directory src --output-file coverage.info
genhtml coverage.info --output-directory out-test-coverage

